sudo: required

language: java

jdk:
  - openjdk8


matrix:
  allow_failures:
    - jdk: openjdk15

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.sonar/cache
    - $HOME/.m2/repository
    - $HOME/.gradle

install: true

script:
  - |
    if [ "$TRAVIS_BRANCH" != "master" -o "$TRAVIS_PULL_REQUEST" == "true" ]; then
        ./mvnw -U verify jacoco:report coveralls:report -B
    fi
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then
        ./mvnw -U verify jacoco:report coveralls:report sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN} -Dsonar.organization=kazuki43zoo -Dsonar.projectKey=kazuki43zoo_mybatis-spring-boot-jpetstore -B
    fi
  - /gradlew clean build


# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - nugunnuguya@naver.com